##
# Ansible playbook for starterkit deployment.
#
# Requires the following parameters called upon playbook execution:
# HOSTNAME: the name of the host
# SERVER_USER: the ssh user to access the server
# WEB_USER: The owning user of the docroot
# GROUP: The group name used by the webserver
# PROJECT_NAME: name of the current project
# DB_SU: The root database username
# DB_SU_PW: The root database user password
# DB_USER: The project database user
# DB_PW: The project database user password
# DB_NAME: The name of the database
# DRUPAL_SU: Drupal administrative user
# DRUPAL_SU_PW: Drupal root user password
# TARGET_FOLDER: /path/to/target/project/folder on the remote
# BACKUP_FOLDER: /path/to/target/backup/folder on the remote
# LOCAL_PROJECT_FOLDER: /path/to/workspace locally
#
##

---
- hosts: $HOSTNAME
  user: $SERVER_USER
  sudo: yes

  vars:
    base: deploy/tasks
    group: $GROUP

  tasks:
    - include: $base/init.yml
    - include: $base/migrate.yml
    - include: $base/finalize.yml
    - include: $base/rollback.yml
