##
# Ansible playbook for starterkit deployment.
# Requires the following parameters called upon playbook execution:
# HOSTNAME: the name of the host
# TARGET_FOLDER: /path/to/target/project/folder on the remote
# BACKUP_FOLDER: /path/to/target/backup/folder on the remote
# PROJECT_NAME: name of the current project
# JENKINS_WORKSPACE: /path/to/jenkins/workspace locally
#
##

---
- name: Create target folder
  file: path=${TARGET_FOLDER} state=directory
  tags:
    - init

- name: Set permissions
  shell: chown -R ${USER}:${GROUP} ${TARGET_FOLDER}
  sudo: yes
  tags:
    - init

- name: Create builds folder
  file: path=${TARGET_FOLDER}/builds state=directory
  tags:
    - init

- name: Create candidate folder
  file: path=${TARGET_FOLDER}/builds/candidate state=directory
  tags:
    - init

- name: Create current folder
  file: path=${TARGET_FOLDER}/builds/current state=directory
  tags:
    - init

- name: Create previous folder
  file: path=${TARGET_FOLDER}/builds/previous state=directory
  tags:
    - init

- name: Create old folder
  file: path=${TARGET_FOLDER}/builds/old state=directory
  tags:
    - init

- name: Create shared folder
  file: path=${TARGET_FOLDER}/shared state=directory
  tags:
    - init

- name: Archive project
  connection: local
  shell: cd ${JENKINS_WORKSPACE}; tar czvf candidate.tar.gz .
  tags:
    - init
    - migrate

- name: Upload tarball to remote
  action: copy src=${JENKINS_WORKSPACE}/candidate.tar.gz dest=${TARGET_FOLDER}/builds/candidate/candidate.tar.gz
  tags:
    - init
    - migrate

- name: Unpack project tarball to candidate
  shell: tar zxf ${TARGET_FOLDER}/builds/candidate/candidate.tar.gz -C ${TARGET_FOLDER}/builds/candidate
  tags:
    - init
    - migrate

- name: Remove candidate build tarball
  action: command rm -f ${TARGET_FOLDER}/builds/candidate/candidate.tar.gz
  tags:
    - init
    - migrate

- name: Set htdocs symlink to candidate
  action: command ln -sfn ${TARGET_FOLDER}/builds/candidate/htdocs ${TARGET_FOLDER}/htdocs
  tags:
   - init
   - migrate

- name: Install profile
  action: command drush --root=${TARGET_FOLDER}/htdocs si ${PROJECT_NAME} --db-su=${DB_SU} --db-su-pw=${DB_SU_PW} --db-url="mysql://${DB_USER}:${DB_PW}@localhost/${DB_NAME}" -y
  tags:
    - init

- name: Update admin password
  action: command drush --root=${TARGET_FOLDER}/htdocs upwd admin --password="${ADMIN_PASS}"
  tags:
    - init

- name: Move drupal files folder to shared folder
  action: command mv ${TARGET_FOLDER}/builds/candidate/htdocs/sites/default/files ${TARGET_FOLDER}/shared/files
  tags:
    - init

- name: Move drupal settings.php file to shared folder
  action: command mv ${TARGET_FOLDER}/builds/candidate/htdocs/sites/default/settings.php ${TARGET_FOLDER}/shared/settings.php
  tags:
    - init

- name: Put site in offline mode
  action: command drush --root=${TARGET_FOLDER}/htdocs vset maintenance_mode 1
  tags:
    - migrate

- name: Backup current site
  action: command drush --root=${TARGET_FOLDER}/htdocs sql-dump --result-file=${BACKUP_FOLDER}/current.sql
  tags:
    - migrate

- name: Symlink drupal files folder to shared files folder
  action: command ln -sfn ${TARGET_FOLDER}/shared/files ${TARGET_FOLDER}/builds/candidate/htdocs/sites/default/files
  tags:
    - init
    - migrate

- name: Symlink drupal settings.php to shared settings.php file
  action: command ln -sfn ${TARGET_FOLDER}/shared/settings.php ${TARGET_FOLDER}/builds/candidate/htdocs/sites/default/settings.php
  tags:
    - init
    - migrate

