##
# Ansible playbook for starterkit deployment.
# Requires the following parameters called upon playbook execution:
# HOSTNAME: the name of the host
# TARGET_FOLDER: /path/to/target/project/folder on the remote
# BACKUP_FOLDER: /path/to/target/backup/folder on the remote
# PROJECT_NAME: name of the current project
# JENKINS_WORKSPACE: /path/to/jenkins/workspace locally
#
##

---
- name: Create target folder
  file: path=${TARGET_FOLDER} state=directory
  tags:
    - init

- name: Create builds folder
  file: path=${TARGET_FOLDER}/builds state=directory
  tags:
    - init

- name: Create candidate folder
  file: path=${TARGET_FOLDER}/builds/candidate state=directory
  tags:
    - init

- name: Create current folder
  file: path=${TARGET_FOLDER}/builds/current state=directory
  tags:
    - init

- name: Create previous folder
  file: path=${TARGET_FOLDER}/builds/previous state=directory
  tags:
    - init

- name: Create old folder
  file: path=${TARGET_FOLDER}/builds/old state=directory
  tags:
    - init

- name: Create shared folder
  file: path=${TARGET_FOLDER}/shared state=directory
  tags:
    - init

- name: Archive project
  connection: local
  shell: cd ${JENKINS_WORKSPACE}; tar czvf candidate.tar.gz .
  tags:
    - init
    - migrate

- name: Upload tarball to remote
  action: copy src=${JENKINS_WORKSPACE}/candidate.tar.gz dest=${TARGET_FOLDER}/builds/candidate/candidate.tar.gz
  tags:
    - init
    - migrate

- name: Unpack project tarball to candidate
  action: command tar zxfv ${TARGET_FOLDER}/builds/candidate/candidate.tar.gz -C ${TARGET_FOLDER}/builds/candidate
  tags:
    - init
    - migrate

- name: Remove candidate build tarball
  action: command rm -f ${TARGET_FOLDER}/builds/candidate/candidate.tar.gz
  tags:
    - init
    - migrate
