---
- name: Create target folder
  file: path=${TARGET_FOLDER} state=directory
  tags:
    - init

- name: Create builds folder
  file: path=${TARGET_FOLDER}/builds state=directory
  tags:
    - init

- name: Create candidate folder
  file: path=${TARGET_FOLDER}/builds/candidate state=directory
  tags:
    - init

- name: Create current folder
  file: path=${TARGET_FOLDER}/builds/current state=directory
  tags:
    - init

- name: Create previous folder
  file: path=${TARGET_FOLDER}/builds/previous state=directory
  tags:
    - init

- name: Create old folder
  file: path=${TARGET_FOLDER}/builds/old state=directory
  tags:
    - init

- name: Create shared folder
  file: path=${TARGET_FOLDER}/shared state=directory
  tags:
    - init

- name: Archive project
  connection: local
  shell: cd ${LOCAL_PROJECT_FOLDER}/${PROJECT_NAME}; tar czf ${LOCAL_PROJECT_FOLDER}/candidate.tar.gz .
  sudo: no
  tags:
    - init

- name: Upload tarball to remote
  action: copy src=${LOCAL_PROJECT_FOLDER}/candidate.tar.gz dest=${TARGET_FOLDER}/builds/candidate/candidate.tar.gz
  tags:
    - init

- name: Unpack project tarball to candidate
  shell: tar zxfo ${TARGET_FOLDER}/builds/candidate/candidate.tar.gz -C ${TARGET_FOLDER}/builds/candidate
  tags:
    - init

- name: Remove candidate build tarball
  command: rm -f ${TARGET_FOLDER}/builds/candidate/candidate.tar.gz
  tags:
    - init

- name: Set htdocs symlink to candidate
  command: ln -sfn ${TARGET_FOLDER}/builds/candidate/htdocs ${TARGET_FOLDER}/htdocs
  tags:
   - init

- name: Install profile
  command: drush --root=${TARGET_FOLDER}/htdocs si ${PROJECT_NAME} --db-su=${DB_SU} --db-su-pw=${DB_SU_PW} --db-url=mysql://${DB_USER}:${DB_PW}@localhost/${DB_NAME} -y
  tags:
    - init

- name: Move settings to shared
  command: mv ${TARGET_FOLDER}/htdocs/sites/default/settings.php ${TARGET_FOLDER}/shared/settings.php
  tags:
    - init

- name: Move files to shared
  command: mv ${TARGET_FOLDER}/htdocs/sites/default/files ${TARGET_FOLDER}/shared/files
  tags:
    - init

- name: Symlink drupal files folder to shared files folder
  command: ln -sfn ${TARGET_FOLDER}/shared/files ${TARGET_FOLDER}/builds/candidate/htdocs/sites/default/files
  tags:
    - init

- name: Symlink drupal settings.php to shared settings.php file
  command: ln -sfn ${TARGET_FOLDER}/shared/settings.php ${TARGET_FOLDER}/builds/candidate/htdocs/sites/default/settings.php
  tags:
    - init

- name: Update admin password
  command: drush --root=${TARGET_FOLDER}/htdocs upwd admin --password=${DRUPAL_SU_PW}
  tags:
    - init
