##
# Ansible playbook for starterkit deployment.
# Requires the following parameters called upon playbook execution:
# HOSTNAME: the name of the host
# TARGET_FOLDER: /path/to/target/project/folder on the remote
# DB_NAME: The target production database name
# DB_USER: The target production database mysql user
# DB_PASSWORD: The target production database mysql password
##

---
- name: Replace candidate build htdocs symlink with current symlink
  command: ln -sfn ${TARGET_FOLDER}/builds/current/htdocs ${TARGET_FOLDER}/htdocs
  tags:
    - rollback

- name: Drop current database
  command: mysql --user=${DB_SU} --password=${DB_SU_PW} -h localhost -e "DROP DATABASE IF EXISTS ${DB_NAME};"
  tags:
    - rollback

- name: Create database
  command: mysql --user=${DB_SU} --password=${DB_SU_PW} -h localhost -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME}; GRANT ALL ON ${DB_NAME}.* TO ${DB_USER}@'localhost' IDENTIFIED BY '${DB_PW}';"
  tags:
     - rollback

- name: Restore backup DB
  command: drush sqlc --root=${TARGET_FOLDER}/htdocs < ${BACKUP_FOLDER}/current.sql -y
  tags:
    - rollback

- name: Remove candidate build
  command: rm -rf ${TARGET_FOLDER}/builds/candidate
  tags:
    - rollback

