---
- name: Replace candidate build htdocs symlink with current symlink
  command: ln -sfn ${TARGET_FOLDER}/builds/current/htdocs ${TARGET_FOLDER}/htdocs
  tags:
    - rollback

- name: Drop current database
  mysql_db: db=${DB_NAME} login_user=${DB_SU} login_password=${DB_SU_PW} state=absent
  tags:
    - rollback

- name: Create database
  mysql_db: db=${DB_NAME} login_user=${DB_SU} login_password=${DB_SU_PW} state=present
  tags:
     - rollback

- name: Create database user
  mysql_user: name=${DB_USER} password=${DB_PW} priv=${DB_NAME}.*:ALL  login_user=${DB_SU} login_password=${DB_SU_PW} state=present
  tags:
    - rollback

- name: Restore backup DB
  mysql_db: db=${DB_NAME} target=${BACKUP_FOLDER}/current.sql login_user=${DB_SU} login_password=${DB_SU_PW} state=import
  tags:
    - rollback

- name: Remove candidate build
  command: rm -rf ${TARGET_FOLDER}/builds/candidate
  tags:
    - rollback

